#if 0 out atw_hw_decrypted() as it is currently an unused function as the code calling it is also #if 0'd out.
atw.c:3021:1: error: unused function 'atw_hw_decrypted' [-Werror,-Wunused-function]

ok deraadt@ sthen@